AY2223S1-CS2103T-T10-1/tp

- docs/_config.yml
- docs/_sass/minima/_base.scss
> Update title of project in `docs/_config.yml`

- README.md
Update Acknowledgement with libraries used.
> Update acknowledgement of README.md

- docs/UserGuide.md
Add the guide for `add task` and `delete task` commands into `UserGuide.md`.
> Add guide for adding and deleting tasks

- docs/UserGuide.md
This pull request does the following:
1. Updates user guide for add/delete module section.
2. Fixes a few formatting inconsistencies and grammatical errors.
> Update user guide (add/delete module)

- docs/UserGuide.md
Currently, there are no details in the user guide that specifies how can users add and delete contacts.
Thus, this pull request aims to update user guide with details on addition and deletion of contacts.
In addition, this pull request fixes some formatting issues.
> Update user guide (add/delete contact)

- docs/UserGuide.md
Currently, there are no details in the user guide that specifies how should a user navigate between home page and modules in the program.
Thus, this pull request aims to update user guide with the details on navigating between home page and modules.
In addition, this pull request fixes some formatting issues.
> Update user guide (navigation) 

- docs/UserGuide.md
Currently, there are no details in the user guide that specifies how users can add and delete links.
Thus, this pull request aims to update the user guide with details on addition and deletion of links.
> Update user guide (add/delete link)

- docs/UserGuide.md
Updates the phrasing under 'Format' section to include second person (you, the reader), under the sections of adding and deleting modules.
> Update user guide to engage reader (add and delete module)

- docs/UserGuide.md
I added a newline to try to make the table render correctly on the [user guide](https://ay2223s1-cs2103t-t10-1.github.io/tp/UserGuide.html).
> Add newline to workaround Jekyll rendering issue

- docs/UserGuide.md
To make our user guide more inclusive to users, we now use 'you' when addressing the user
> Update user guide to directly address user (navigation)

- build.gradle
- src/main/java/seedu/address/MainApp.java
Bumps version up to 1.2.1 and renames application file from `addressbook.jar` to `plannit.jar`.
> Release v1.2.1 (trial)

- src/main/java/seedu/address/logic/commands/AddPersonCommand.java
- src/main/java/seedu/address/logic/commands/EditPersonCommand.java
- src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/AddPersonCommandIntegrationTest.java
- src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
- src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
- src/test/java/seedu/address/logic/parser/AddPersonCommandParserTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
- src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
- src/test/java/seedu/address/testutil/PersonUtil.java
This pull request is a refactoring of contact to person to be consistent with class name.
The pull request does the following:
* Update commands to use `person` instead of `contact`
* Refactor code in main and test folder as well
> Rename contact to person

- README.md
- docs/index.md
This pull requests aims to do the following
- Update `docs/index.md` to reflect Plannit instead of AB3
- Update value proposition in `docs/index.md` and `README.md`
This pull request does not update `Ui.png` because we need to create the final product before we can make a real screenshot of the product.
> Update landing page and value proposition

- docs/UserGuide.md
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/logic/commands/AddLinkCommand.java
- src/main/java/seedu/address/logic/commands/ClearCommand.java
- src/main/java/seedu/address/logic/commands/DeleteLinkCommand.java
- src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
- src/main/java/seedu/address/logic/commands/ExitCommand.java
- src/main/java/seedu/address/logic/commands/FindModuleCommand.java
- src/main/java/seedu/address/logic/commands/FindPersonCommand.java
- src/main/java/seedu/address/logic/commands/HelpCommand.java
- src/main/java/seedu/address/logic/commands/ListPersonCommand.java
- src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
- src/main/java/seedu/address/logic/parser/DeleteModuleCommandParser.java
- src/main/java/seedu/address/logic/parser/EditModuleCommandParser.java
- src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
- src/main/java/seedu/address/logic/parser/FindModuleCommandParser.java
- src/main/java/seedu/address/logic/parser/FindPersonCommandParser.java
- src/main/java/seedu/address/logic/parser/GoToCommandParser.java
- src/main/java/seedu/address/model/module/ModuleTitle.java
1. Improve Javadoc comments and messages.
2. Update UserGuide.md to reflect changes in codes
> Fix errors in documentation

- docs/UserGuide.md
This pull request fixes the missing `delete-person-from-module` command row.
> Fix missing `delete-person-from-module` command row

- docs/UserGuide.md
(Resolves https://github.com/AY2223S1-CS2103T-T10-1/tp/issues/131)
Rephrased sentence to be more precise on what is shown when one navigates to a particular module
(Resolves https://github.com/AY2223S1-CS2103T-T10-1/tp/issues/127)
Included notes on how to view added person
(Resolves https://github.com/AY2223S1-CS2103T-T10-1/tp/issues/144)
Included notes to highlight implication of using `add-module`
Included notes to highlight implication of using `delete-module`
Included notes to highlight implication of using `add-person`
Included tips to improve user-friendliness
Included notes to highlight implication of using `home`
Included tips to improve user-friendliness
Included notes to highlight implication of using `goto`
> Update user guide (Navigation)

- docs/UserGuide.md
Appearance of Notes and Tips column did not match expectation
This PR attempts to
1. Fix broken table formatting
2. Fix Notes and Tips column
> Fix display on website

- docs/UserGuide.md
Currently, there is no mentioning of case-sensitivity in the user guide.
Thus this pull request aims to:
* add case-sensitivty constraints in flag table
> Add case-sensitivty constraints in flag table

- docs/team/tan-jia-rong.md
Added rough framework for project portfolio page
> Implement draft project portfolio page

- docs/team/ekweirui.md
Update @ekweirui PPP to have the lastest contributions.
> Update PPP with latest contributions

- docs/team/ekweirui.md
Update PPP to 
* include the latest discussions based on what we discussed during the tutorial session on the 3rd of November
* adopt suggestions by @cheeheng
> Update PPP to include `addPersonToModule`

- docs/team/teoyuqi.md
Fix minor typos and inconsistencies in this PR.
> Update PPP (Minor typos and inconsistencies)

- docs/DeveloperGuide.md
This PR changes all occurrences of `::` to `#`
> Change `::` to `#`

- docs/UserGuide.md
Remove code snippets from headings
> Fix headings for `Task`

- docs/AboutUs.md
- docs/team/cheeheng.md
Changes made in this pull request
- Include highlights of add/delete/edit module
- Minor formatting changes
> Update project portfolio page

- src/main/java/seedu/address/MainApp.java
> Prepare to release v1.4

- docs/AboutUs.md
> Minor changes to PPP

- docs/UserGuide.md
1. Fix table width issues
2. Fix inconsistent UG infoboxes
> Fix formatting in UG (`swap-task`)

- docs/AboutUs.md
- docs/team/tan-jia-rong.md
> Update Portfolio Page

- docs/team/teoyuqi.md
> Fix grammatical error in PPP

- docs/AboutUs.md
- docs/team/ekweirui.md
Reduce lines of code in PPP to comply with the 2-page constraint.
> Reduce lines of code

- docs/team/cheeheng.md
Fix minor inconsistencies in PPP
- Fix grammatical error
- Update to include release of v1.4
> Fix minor inconsistencies in PPP

- docs/UserGuide.md
Fixed formatting issues
Improve on screenshots formatting and descriptions
Fix broken hyperlinks
> Update minor formatting issues

- docs/team/tan-jia-rong.md
Added page break to ensure heading is on same page as content
> Update PPP formatting

- README.md
- docs/UserGuide.md
Add brief description of tasks at top of UG, as suggested by @ekweirui and @cheeheng
> Add description on tasks in UG

- docs/UserGuide.md
Update the constraints column to have the same format for all columns.
> Update constraints column to have same format

- docs/UserGuide.md
Currently, the UG does not feel very user-friendly.
Thus, this pull request adds user stories to make it feel more inviting for users.
> Add user stories in UG

- docs/DeveloperGuide.md
Add manual testing instruction for clear.
> Add test instruction for clear

- docs/UserGuide.md
Unfortunately, this typo slipped through when we submitted for CS2103T. Let's try to fix it for CS2101.
> Fix typo in UG
